circuits/urls.py
from django.urls import path
from .views import (
    CircuitsListView, 
    CircuitDescriptionsListView,
    CircuitUpdateView,
    
)

app_name = 'circuits'

urlpatterns = [
    path('', CircuitsListView.as_view(), name='main'),
    path('list/<pk>', CircuitDescriptionsListView.as_view() , name='circuit-descriptions-list'),
    path('update/<int:pk>', CircuitUpdateView.as_view() , name='circuit-update'),
    

]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import home_view, change_theme
from circuits.views import CircuitsListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='main'),
    path('switch/', change_theme, name='change'),
    path('circuits/', include('circuits.urls', namespace='circuits')),
    path('descriptions/', include('descriptions.urls', namespace='descriptions')),
    path('__reload__/', include('django_browser_reload.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Electrical Circuits Administration'
admin.site.index_title = 'Manage the Circuits System'

descriptions/urls.py
from django.urls import path
from .views import (
    DescriptionsListView, 
    CircuitDescriptionUpdateView,
    circuit_descriptions_generation_view,
    circuit_descriptions_run_view
)

app_name = 'descriptions'

urlpatterns = [
    path('', DescriptionsListView.as_view(), name='main'),
    path('update/<int:pk>', CircuitDescriptionUpdateView.as_view() , name='circuit-description-update'),
    path('generation/<int:pk>', circuit_descriptions_generation_view , name='circuit-descriptions-generation'),
    path('run/<int:pk>', circuit_descriptions_run_view , name='generation-run'),

]

descriptions/models.py
from django.db import models
from django.urls import reverse
from circuits.models import Circuit
from django.utils.text import slugify

class Description(models.Model):
    """
    Description class
    """
    circuit_id = models.ForeignKey(Circuit, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    cycle = models.SmallIntegerField(default=1)
    event = models.SmallIntegerField(default=1)
    event_date = models.DateTimeField(null=True, editable = True)
    event_duration = models.SmallIntegerField(default=5)
    circuit_slug = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return f"{self.circuit_id} - {self.cycle} - {self.event} " 

    def get_absolute_url(self):
        circuit_slug = self.circuit_slug
        return reverse("circuits:circuit-descriptions-edit", {"circuit_slug": circuit_slug})
    
    def get_absolute_url_b(self):
        pk = self.pk
        return reverse("descriptions:circuit-description-detail", {"pk": pk})
    

descriptions/forms.py
from django import forms
from .models import Description
from django.core.exceptions import ValidationError

class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = '__all__'
    
    #def clean(self):
    #    circuit_slug = self.cleaned_data.get('circuit_id')

        #if len(str(circuit_id)) < 4:
        #    error_msg = 'the circuit id is too short'
        #    #self.add_error('circuit_id',error_msg)
        #    raise ValidationError(error_msg)

        #elif len(str(circuit_id)) > 4:
        #    error_msg = 'The circuit id is too long'
        #    #self.add_error('circuit_id',error_msg)
        #    raise ValidationError(error_msg)

      
        #return self.cleaned_data

            

descriptions/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from django.http import HttpResponse
from .models import Description
from .forms import DescriptionForm
from circuits.models import Circuit 
from .models import Description
from django.contrib import messages
from django.views.generic import (
    ListView, 
    DetailView,
    UpdateView,
    CreateView,
)
# Create your views here.
class DescriptionsListView(ListView):
    model = Description
    template_name = 'descriptions/main.html'
    queryset = Description.objects.all()
    qs = queryset
    #print(qs)
    context_object_name = 'qs'


class CircuitDescriptionUpdateView(UpdateView):
    model = Description
    template_name = 'descriptions/circuit_description_update.html'
    fields = '__all__'
    from_class = DescriptionForm

    def get_object(self):
        pk_ = self.kwargs.get('pk')
        #obj = Description.objects.get(pk=pk_) # alternativa de comando al siguiente
        obj = get_object_or_404(Description, pk=pk_)
        return obj

def circuit_descriptions_generation_view(request, **kwargs):
    pk_ = kwargs.get('pk')
    obj = get_object_or_404(Circuit, pk=pk_)
    i_instance = None
    print(obj)
    context = {
        'obj': obj,
    }
    #return render(request, 'descriptions/circuit_descriptions_generation.html')
    print(context)
    print(request)
    return render(request, 'descriptions/circuit_descriptions_generation.html', context)

def circuit_descriptions_run_view(request, **kwargs):
    print("run")
    #if request.method=='POST':

    pk_ = kwargs.get('pk')
    obj = get_object_or_404(Circuit, pk=pk_)
    print("run ")
    # primero se borran todos las descriptions del circuito seleccionado
    Description.objects.filter(circuit_id_id = pk_ ).delete()
    
    # loop por cada circuito, se corren num_cycles
    for i in range(obj.num_cycles):
        i = i + 1
        # loop por cada circuito, se corren num_events
        for j in range(obj.num_events):
            j = j + 1
            
            cycle = i
            event = j
            event_duration = obj.event_duration
            #item1.event_random 
            data = Description(circuit_id_id=obj.circuit_id,cycle=i, event=j, event_duration=obj.event_duration)
            #print(data)

            exist = Description.objects.filter(circuit_id=obj.circuit_id,cycle=cycle,event=event).exists()
            print(exist)
            if not exist:
                circuit_slug = slugify(f"{obj.circuit_id} {cycle} {event}")
                print(circuit_slug)
                Description.objects.create(circuit_id_id=obj.id,cycle=i, event=j, event_duration=obj.event_duration, circuit_slug=circuit_slug)
                
    #messages.add_message(request, messages.INFO, f"Circuit: {circuit_slug} has been generated" )
    
    context = {
        'obj': obj,
    }
    
    return render(request, 'descriptions/circuit_descriptions_run.html', context)
    

descriptions/templates/descriptions/circuit_description_update.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block scripts %}
    <script src="{% static 'circuits/main.js' %}" defer></script>	
    <script src="{% static 'js/form_modal2.js' %}" defer></script>	
{% endblock scripts %}

% endblock title %}

{% block content %}
  {% include "components/header.html" with title=obj.circuit_slug description="Circuit Description Detail" is_go_back=True %}

  {% if messages %}
  {% for message in messages %}
      {% if 'info' in message.tags %}
          {% include 'components/alert.html' with is_info=True title='Success' body=message %}
      {% elif 'error' in message.tags %}
          {% include 'components/alert.html' with is_info=False title='Error' body=message %}
      {% endif %}
  {% endfor %}
{% endif %}

<!-- form modal -->
<div id="form-modal" class="relative z-50" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
    <div class="fixed inset-0 z-10 overflow-y-auto">
        <div id="backdrop" class="flex min-h-full items-center justify-center p-4 text-center">
            <div class="relative transform overflow-hidden rounded-lg text-left shadow-xl transition-all my-8">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="bg-white dark:text-white dark:bg-slate-300 pt-5 pb-4 px-8">
                        <div class="mt-3 text-left">
                            <h3 id="modal-title" class="text-2xl font-medium leading-6 text-gray-900" >
                                edit description
                            </h3>
                            <div class="mt-3">
                                <div class="mb-2">
                                    <label for="{{ form.circuit_slug.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Circuit Slug
                                    </label>
                                    {{form.circuit_slug|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.circuit_slug.errors %}
                                        {% for error in form.circuit_slug.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.cycle.id_for_label }}"
                                        class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Cycle
                                    </label>
                                    {{form.cycle|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.cycle.errors %}
                                        {% for error in form.cycle.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.event.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Event
                                    </label>
                                    {{form.event|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.event.errors %}
                                        {% for error in form.event.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.event.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Event Duration
                                    </label>
                                    {{form.event_duration|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.event_duration.errors %}
                                        {% for error in form.event_duration.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.event_date.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Event Date Time
                                    </label>
                                    {{form.event_date|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.event_date.errors %}
                                        {% for error in form.event_date.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bg-gray-50 dark:text-white dark:bg-slate-400 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                        <button type="submit" class="bg-transparent hover:bg-blue-500 text-blue-800 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                            save
                        </button>
                        <button type="button" id="cancel-btn" class="bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 border border-red-600 rounded mr-3">
                            cancel
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>




{% endblock content %}

descriptions/templates/descriptions/circuit_descriptions_generation.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block scripts %}
    
{% endblock scripts %}

{% block title %}circuit descriptions generation {% endblock title%}

{% block content %}
{% include 'components/header.html' with title='Circuits Generation' descriptions='Circuit Descriptions Generation' is_form_available=True icon="<i class='fa-solid fa-arrow-left'></i> " %}

    {% if messages %}
        {% for message in messages %}
            {% if 'info' in message.tags %}
                {% include 'components/alert.html' with is_info=True title='Success' body=message %}
            {% elif 'error' in message.tags %}
                {% include 'components/alert.html' with is_info=False title='Error' body=message %}
            {% endif %}
        {% endfor %}
    {% endif %}

    
    <div class="relative z-50" aria-labelledby="modal-title" aria-modal="true">
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
        <div class="fixed inset-0 z-10 overflow-y-auto">
            <div class="flex min-h-full items-center justify-center p-4 text-center">
                <div class="relative transform overflow-hidden rounded-lg text-left shadow-xl transition-all my-8">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="bg-white dark:text-white dark:bg-slate-300 pt-5 pb-4 px-8">
                            <div class="mt-3 text-left">
                                <h2 class="text-2xl font-medium leading-6 text-gray-900">
                                    circuit generation process for
                                </h2>
                                <div class="mt-3">
                                     <div class="mb-2">
                                            <label for="{{form.circuit_id.id_for_label}}"
                                            class="block font-bold text-slate-800 dark:text-slate-500"
                                            > 
                                            Circuit ID: 
                                                <div class="bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full" 
                                                >
                                                {{ obj.circuit_id }}
                                                </div>
                                            </label> 
                                           
                                            {{form.circuit_id|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                            {% if form.circuit_id.errors %}
                                                {% for error in form.circuit_id.errors %}
                                                    <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}

                                            
                                        </div>
                                </div>
                            </div>
                        </div>
                        <div class="bg-gray-50 dark:text-white dark:bg-slate-400 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6"
                            >
                            <a href="{% url 'descriptions:generation-run' obj.pk %}"
                            class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" 
                            >
                            run
                        </a>
                            <button type="button"  href="{% url 'circuits:circuit-descriptions-list' obj.pk " class="bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 border border-red-600 rounded mr-3"
                                >
                                cancel
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

descriptions/templates/descriptions/circuit_descriptions_generation2.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block scripts %}
    <script src="{% static 'circuits/main.js' %}" defer></script>	
    <script src="{% static 'js/form_modal2.js' %}" defer></script>	
{% endblock scripts %}

{% block title %}circuit descriptions generation {% endblock title%}

{% block content %}
{% include 'components/header.html' with title='Circuits Generation' descriptions='Circuit Descriptions Generation' is_form_available=True icon="<i class='fa-solid fa-arrow-left'></i> " %}

    {% if messages %}
        {% for message in messages %}
            {% if 'info' in message.tags %}
                {% include 'components/alert.html' with is_info=True title='Success' body=message %}
            {% elif 'error' in message.tags %}
                {% include 'components/alert.html' with is_info=False title='Error' body=message %}
            {% endif %}
        {% endfor %}
    {% endif %}

    <!-- form modal -->
    <div id="form-modal" class="relative z-50" aria-labelledby="modal-title" role="dialog" aria-modal="true">
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
        <div class="fixed inset-0 z-10 overflow-y-auto">
            <div id="backdrop" class="flex min-h-full items-center justify-center p-4 text-center">
                <div class="relative transform overflow-hidden rounded-lg text-left shadow-xl transition-all my-8">
                    <form id="generationRunForm" method="post">
                        {% csrf_token %}
                        <div class="bg-white dark:text-white dark:bg-slate-300 pt-5 pb-4 px-8">
                            <div class="mt-3 text-left">
                                <h2 id="modal-title" class="text-2xl font-medium leading-6 text-gray-900">
                                    circuit generation process for
                                </h2>
                                <div class="mt-3">
                                     <div class="mb-2">
                                            
                                            <label for="{{form.circuit_id.id_for_label}}"
                                            class="block font-bold text-slate-800 dark:text-slate-500"
                                            > 
                                            Circuit ID: 
                                                <div class="bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full" 
                                                id="cicuit" data-id="{{ obj.pk }}"
                                                >
                                                {{ obj.circuit_id }}
                                                </div>
                                            </label> 
                                           
                                            {{form.circuit_id|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                            {% if form.circuit_id.errors %}
                                                {% for error in form.circuit_id.errors %}
                                                    <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}

                                            
                                        </div>
                                </div>
                            </div>
                        </div>
                        <div class="bg-gray-50 dark:text-white dark:bg-slate-400 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
        
                            <button type="button" id="runButton" class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" data-url="{% url 'descriptions:generation-run' obj.pk %}"
                                >
                                run  
                            </button>
                            <button type="button" id="cancel-btn" class="bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 border border-red-600 rounded mr-3"
                                >
                                cancel
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock content %}

descriptions/templates/descriptions/circuit_descriptions_run.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block scripts %}
{% endblock scripts %}

{% block title %}circuit descriptions running {% endblock title%}

{% block content %}
{% include 'components/header.html' with title='Circuits Generation Run' descriptions='Circuit Descriptions Generation' is_form_available=True icon="<i class='fa-solid fa-arrow-left'></i> " %}

    {% if messages %}
        {% for message in messages %}
            {% if 'info' in message.tags %}
                {% include 'components/alert.html' with is_info=True title='Success' body=message %}
            {% elif 'error' in message.tags %}
                {% include 'components/alert.html' with is_info=False title='Error' body=message %}
            {% endif %}
        {% endfor %}
    {% endif %}

{% endblock content %}

descriptions/templates/descriptions/main.html
{% extends 'base.html' %}

{% block title %} Descriptions List{% endblock title %}

{% block content %}

<h1>Descriptions List</h1>

{% if qs %}
    <ul>
        {% for obj in qs %}
            <li> 
                <a href="#" 
                >
                {{ obj.circuit_slug }} {{ obj.circuit_id.circuit_description}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    No descriptions registered
{% endif %}

{% endblock content %}