circuits/urls.py
from django.urls import path
from .views import (
    CircuitsListView, 
    CircuitDescriptionsListView,
    CircuitUpdateView,
    
)

app_name = 'circuits'

urlpatterns = [
    path('', CircuitsListView.as_view(), name='main'),
    path('list/<pk>', CircuitDescriptionsListView.as_view() , name='circuit-descriptions-list'),
    path('update/<int:pk>', CircuitUpdateView.as_view() , name='circuit-update'),
    

]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import home_view, change_theme
from circuits.views import CircuitsListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='main'),
    path('switch/', change_theme, name='change'),
    path('circuits/', include('circuits.urls', namespace='circuits')),
    path('descriptions/', include('descriptions.urls', namespace='descriptions')),
    path('__reload__/', include('django_browser_reload.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Electrical Circuits Administration'
admin.site.index_title = 'Manage the Circuits System'

descriptions/urls.py
from django.urls import path
from .views import (
    DescriptionsListView, 
    CircuitDescriptionUpdateView,
    circuit_descriptions_generation_view,
    circuit_descriptions_run_view
)

app_name = 'descriptions'

urlpatterns = [
    path('', DescriptionsListView.as_view(), name='main'),
    path('update/<int:pk>', CircuitDescriptionUpdateView.as_view() , name='circuit-description-update'),
    path('generation/<int:pk>', circuit_descriptions_generation_view , name='circuit-descriptions-generation'),
    path('run/<int:pk>', circuit_descriptions_run_view , name='generation-run'),

]

circuits/models.py
from django.db import models
from django.urls import reverse

class Circuit(models.Model):
    """
    Circuit class
    """
    circuit_id = models.SmallIntegerField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    circuit_description = models.CharField(max_length=100)
    circuit_status = models.BooleanField(default=True)
    num_cycles = models.SmallIntegerField(editable=True, default=1)
    num_events = models.SmallIntegerField(editable=True, default=1)
    event_duration = models.SmallIntegerField(default=5)
    event_date = models.DateTimeField(null=True, editable=True)
    event_random = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.circuit_id}" 
    
    def get_absolute_url(self, *args, **kwargs):
        return reverse("circuits:circuit-descriptions-list", kwargs={"pk": self.pk})
    
    # reverse relationship
    # esta propiedad permitira manejar descriptions como un campo de la clase anterior
    @property
    def descriptions(self):
        return self.description_set.all()  # description en singular, _set.all() tiene que ir por reverse relationship
    

circuits/forms.py
from django import forms
from .models import Circuit
from django.core.exceptions import ValidationError

class CircuitForm(forms.ModelForm):
    class Meta:
        model = Circuit
        fields = '__all__'

    def clean(self):
        circuit_id = self.cleaned_data.get('circuit_id')

        if len(str(circuit_id)) < 4:
            error_msg = 'the circuit id is too short'
            #self.add_error('circuit_id',error_msg)
            raise ValidationError(error_msg)

        elif len(str(circuit_id)) > 4:
            error_msg = 'The circuit id is too long'
            #self.add_error('circuit_id',error_msg)
            raise ValidationError(error_msg)

        num_cycles = self.cleaned_data.get('num_cycles')
        if num_cycles < 1:
            error_msg = 'Number of cycles has to be greater than 1'
            #self.add_error('num_cycles',error_msg)
            raise ValidationError(error_msg)
        
        num_events = self.cleaned_data.get('num_events')
        if num_events < 1:
            error_msg = 'Number of events has to be greater than 1'
            #self.add_error('num_events',error_msg)
            raise ValidationError(error_msg)
        
        circuit_exists = Circuit.objects.filter(circuit_id__iexact=circuit_id).exists()
        if circuit_exists:
            error_msg = 'Circuit already exists'
            raise ValidationError(error_msg)

        return self.cleaned_data

            

circuits/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from .models import Circuit
from descriptions.models import Description
from .forms import CircuitForm
from django.views.generic import (
    ListView, 
    FormView,
    DetailView,
    UpdateView,
    CreateView
)
from .forms import CircuitForm
from django.urls import reverse, reverse_lazy
from django.contrib import messages
# para trabajar con letras del abecedario
import string

# Create your views here.

class CircuitsListView(FormView, ListView):
    model = Circuit
    # por omisión: circuit_list.html
    # por omisión: object_list
    # para evitar lo anterior, cambiaremos los nombres:
    template_name = 'circuits/main.html'
    queryset = Circuit.objects.all().order_by('circuit_id')
    qs = queryset
    context_object_name = 'qs'
    form_class = CircuitForm

    i_instance = None

    #success_url = reverse_lazy('circuits:main')
    
    # overridinig success_url method
    def get_success_url(self):
        return self.request.path

    #def get_queryset(self):
    #    parameter = 's'
    #    return Program.objects.filter(title_startswith=parameter=) 

    #def get_context_data(self):
    #    context = { 
    #        'form': self.get_form_class(), 
    #        'qs': self.get_queryset(),
    #        'hi': 'hello',
    #        'hi2': 'maryita'
    #    }
    #    return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # abajo otros parametros a pasar al html:
        # context['hi'] = 'un parametro '
        # context['hi2'] = 'otro parametro'
        # las siguientes 2 lineas no sirven en este programa
        #letters = list(string.ascii_uppercase)
        #context['letters'] = letters
    
        return context

    # esto garantiza que se guarde el formulario en la base de datos
    def form_valid(self, form):
        self.i_instance = form.save()
        messages.add_message(self.request, messages.INFO, f"Circuit: {self.i_instance.circuit_id} has been created" )
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print(form.errors)
        self.object_list = self.get_queryset() # a veces se pierde el object_list, hay que reasignarlo
        messages.add_message(self.request, messages.ERROR, form.errors)
        return super().form_invalid(form)

class CircuitDescriptionsListView(ListView):
    model = Circuit
    template_name = 'circuits/circuit_descriptions_list.html'
    #paginate_by = 5
    #context_list llevara los objetos
    #form_class = CircuitForm

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        #obj = Circuit.objects.get(pk=pk)  # es la referencia del objeto padre
        #descriptions = obj.descriptions  # por una property se trata como que fuera un campo
        return Circuit.objects.get(pk=pk).descriptions


#def circuit_descriptions_list_view(request, **kwargs):
#    pk = kwargs.get('pk')
#    obj = Circuit.objects.get(pk=pk)  # es la referencia del objeto padre
#    descriptions = obj.descriptions  # por una property se trata como que fuera un campo
#
#    context = {
#        'obj': obj,
#        'descriptions': descriptions,
#    }
#    return render(request, 'circuits/circuit_descriptions_list.html', context)

class CircuitUpdateView(UpdateView):
    model = Circuit
    template_name = 'circuits/circuit_update.html'
    fields = '__all__'
    #form_class = CircuitForm

    def get_object(self):
        pk_ = self.kwargs.get('pk')
        #obj = Circuit.objects.get(pk=pk_) # alternativa de comando al siguiente
        obj = get_object_or_404(Circuit, pk=pk_)
        print(obj.pk)
        return obj
    

circuits/templates/circuits/circuit_descriptions_list.html
{% extends 'base.html' %}

{% block title %}Circuit Descriptions {% endblock title %}

{% block content %}

{% include "components/header.html" with title=object.descriptions.circuit_id description="Circuit Descriptions" is_go_back=True %}
<!---<h2>{{ obj.circuit_id }} - {{ obj.circuit_description }}</h2>--->

{% if object_list %}
    
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase dark:bg-gray-700 dark:text-gray-400">
            <tr class="border">
                <th scope="col" class="py-3 px-6">
                    #
                </th>
                <th scope="col" class="py-3 px-6">
                    Circuit ID Slug
                </th>
                <th scope="col" class="py-3 px-6">
                    Circuit ID
                </th>
                <th scope="col" class="py-3 px-6">
                    Cycle
                </th>
                <th scope="col" class="py-3 px-6">
                    Event
                </th>
                <th scope="col" class="py-3 px-6">
                    Event Duration
                </th>
                <th scope="col" class="py-3 px-6">
                    Event Date
                </th>
                <th scope="col" class="py-3 px-6">
                    edit
                </th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr class="border-b dark:bg-gray-400 dark:border-gray-700 {% if not obj.is_read  %}font-bold{% endif %}">
                <td scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{ forloop.counter }}
                </td>
                <td class="py-4 px-6 font-medium text-white text-gray-900 whitespace-nowrap">
                    {{ obj.circuit_slug }}
                </td>
                <td class="py-4 px-6 font-medium text-white text-gray-900 whitespace-nowrap">
                    {{ obj.circuit_id }}
                </td>
                <td class="py-4 px-6 font-medium text-white text-gray-900 whitespace-nowrap">
                    {{ obj.cycle }}
                </td>
                <td class="py-4 px-6 font-medium text-white text-gray-900 whitespace-nowrap">
                    {{ obj.event }}
                </td>
                <td class="py-4 px-6 font-medium text-white text-gray-900 whitespace-nowrap">
                    {{ obj.event_duration }}
                </td>
                <td class="py-4 px-6 font-medium text-white text-gray-900 whitespace-nowrap">
                    {{ obj.event_date }}
                </td>
                <td class="py-4 px-6">
                    {% comment %}
                    {% include 'components/buttons/edit_button.html' with href=obj.get_absolute_url_b %}
                    {% endcomment %}
                    <a href="{% url 'descriptions:circuit-description-update' obj.pk %}"
                    class="bg-sky-500 hover:bg-sky-600 text-white rounded-xl p-3"
                    >
                    <i class="fa-solid fa-pencil"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

    {% comment %}
    {% if is_paginated %}
        <div class="mt-3">
            <ul class="inline-flex items-center -space-x-px">
    
                {% if page_obj.has_previous %}
                    <li>
                        <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% else %} href="" {% endif %} class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-200 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">                    
                            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                        </a>
                    </li>
                {% endif %}
    
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li><a class="px-3 py-2 leading-tight text-gray-500 dark:text-gray-100 bg-gray-200 dark:bg-gray-700 border border-gray-300 hover:bg-white hover:text-gray-700  dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white" href="?page={{ i }}">{{ i }}</a></li>
                    {% else %}
                        <li><a class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
    
                {% if page_obj.has_next %}
                    <li>
                        <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% else %} href="" {% endif %} class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-200 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">                    
                            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% else %}
        No descriptions registered
    {% endif %}
    {% endcomment %}
<br>

{% endblock content %}

circuits/templates/circuits/circuit_update.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block scripts %}
    <script src="{% static 'circuits/main.js' %}" defer></script>	
    <script src="{% static 'js/form_modal2.js' %}" defer></script>	
{% endblock scripts %}

% endblock title %}

{% block content %}
  {% include "components/header.html" with title=obj.circuit_id description="Circuit Detail" is_go_back=True %}

  {% if messages %}
  {% for message in messages %}
      {% if 'info' in message.tags %}
          {% include 'components/alert.html' with is_info=True title='Success' body=message %}
      {% elif 'error' in message.tags %}
          {% include 'components/alert.html' with is_info=False title='Error' body=message %}
      {% endif %}
  {% endfor %}
{% endif %}

<!-- form modal -->
<div id="form-modal" class="relative z-50" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
    <div class="fixed inset-0 z-10 overflow-y-auto">
        <div id="backdrop" class="flex min-h-full items-center justify-center p-4 text-center">
            <div class="relative transform overflow-hidden rounded-lg text-left shadow-xl transition-all my-8">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="bg-white dark:text-white dark:bg-slate-300 pt-5 pb-4 px-8">
                        <div class="mt-3 text-left">
                            <h3 id="modal-title" class="text-2xl font-medium leading-6 text-gray-900" >
                                edit circuit
                            </h3>
                            <div class="mt-3">
                                <div class="mb-2">
                                    <label for="{{ form.circuit_id.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Circuit Id
                                    </label>
                                    {{form.circuit_id|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.circuit_id.errors %}
                                        {% for error in form.circuit_id.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.circuit_description.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Circuit Description
                                    </label>
                                    {{form.circuit_description|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.circuit_description.errors %}
                                        {% for error in form.circuit_description.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.circuit_status.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Circuit Status
                                    </label>
                                    {{form.circuit_status|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.circuit_status.errors %}
                                        {% for error in form.circuit_status.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.num_cycles.id_for_label }}"
                                        class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Number of Cycles
                                    </label>
                                    {{form.num_cycles|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.num_cycles.errors %}
                                        {% for error in form.num_cycles.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.num_events.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Number of Events
                                    </label>
                                    {{form.num_events|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.num_events.errors %}
                                        {% for error in form.num_events.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.event_duration.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Event Duration
                                    </label>
                                    {{form.event_duration|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.event_duration.errors %}
                                        {% for error in form.event_duration.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-2">
                                    <label for="{{ form.event_random.id_for_label }}"
                                    class="block font-bold text-slate-800 dark:text-slate-500"
                                    > Event Random
                                    </label>
                                    {{form.event_random|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full'}}
                                    {% if form.event_random.errors %}
                                        {% for error in form.event_random.errors %}
                                            <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bg-gray-50 dark:text-white dark:bg-slate-400 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                        <button type="submit" class="bg-transparent hover:bg-blue-500 text-blue-800 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                            save
                        </button>
                        <button type="button" id="cancel-btn" class="bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 border border-red-600 rounded mr-3">
                            cancel
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>




{% endblock content %}

circuits/templates/circuits/circuits_list.html
{% extends 'base.html' %}


{% block content %}

{% if qs %}
<br>
<br>
<br>
    <ul>
        {% for obj in qs %}
            <li> <a href="" {{ obj.circuit_id }} {{ obj.circuit_description }}.... ></a></li>
        {% endfor %}
    </ul>
{% else %}
    No circuits registered yet
{% endif %}

<a href="{% url 'circuits:main' %}" class="btn btn-danger">Descripciones></a>

{% endblock content %}