core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import home_view, change_theme
from circuits.views import CircuitsListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='main'),
    path('switch/', change_theme, name='change'),
    path('circuits/', include('circuits.urls', namespace='circuits')),
    path('descriptions/', include('descriptions.urls', namespace='descriptions')),
    path('__reload__/', include('django_browser_reload.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Electrical Circuits Administration'
admin.site.index_title = 'Manage the Circuits System'

templates/layout/navbar.html
<nav class="fixed flex items-center h-16 bg-gradient-to-r from-cyan-500 to-blue-700 mb-2 w-full z-10 text-white">
    <div class="flex justify-between w-full px-4 py-3">
        <div>
            logo
        </div>
        <div>
            avatar & menu
        </div>
    </div>
</nav>

templates/layout/sidebar.html
{% url 'main' as path_to_home %}
{% url 'circuits:main' as path_to_circuits %}
{% url 'descriptions:main' as path_to_descriptions %}


<aside class="hidden md:block sticky bg-slate-900 h-screen text-white w-full pt-24 text-sm">
    <ul>
        <li class="mb-6 mx-auto">
            <a href="" class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500">
                <i class="fa-solid fa-chart-pie fa-xl"></i>
                <p>dashboard</p>
            </a>
        </li>
        <li class="mb-6 mx-auto">
            <a href=" {{ path_to_circuits }} " class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500">
                <i class="fa-solid fa-books fa-xl"></i>
                <p>circuits</p>
            </a>
        </li>
        <li class="mb-6 mx-auto">
            <a href=" {{ path_to_descriptions }} " class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500">
                <i class="fa-solid fa-books fa-xl"></i>
                <p>descriptions</p>
            </a>
        </li>
    </ul>
</aside>